@startuml C4_Container
!include <C4/C4_Container>

LAYOUT_TOP_DOWN()

Person(user, "User", "Взаимодействует с платформой")
System_Boundary(c1, "Краудфандинговые платформа") {
    Container(web_client, "Web App", "Next js", $descr="Предоставляет доступ к краудфандинговой платформы")
    Container(api_gateway, "API Gateway", "Kong", $descr="Управляет маршрутизацией запросов между клиентами и микросервисами. Авторизация и аутентификация. мониторинг и логирование микросервисов")
    Container(auth_service, "Auth Service", "Axum", $descr="Управляет пользователями")
    Container(project_service, "Project Service", "Axum", $descr="Управляет проектами")
    Container(payment_service, "Payment Service", "Fastify", $descr="Управляет платежами")
    Container(notification_service, "Notification Service", "Axum", $descr="Управляет уведомлениями")
    Container(chat_service, "Chat Service", "Axum", $descr="Управляет чатами")
    ContainerQueue(kafka, "Kafka",  $descr="Организует очередь сообщений")
    ContainerDb(project_db, "Project DB","Elasticsearch",  $descr="Хранит проекты")
    ContainerDb(user_db, "User DB","Postgres",  $descr="Хранит пользователей")
    ContainerDb(payment_db, "Payment DB","Postgres",  $descr="Хранит инофрмацию о платежах")
    ContainerDb(chat_db, "Chat DB","MongoDB",  $descr="Хранит чаты")
    ContainerDb(redis, "Redis",  $descr="Хранит кэшированные данные")
}
    Container_Ext(firebase, "Firebase",  $descr="Отправляет push-уведомления")

Rel(user, web_client, "Uses", "HTTPS")
Rel(web_client, api_gateway, "Uses", "REST/GRAPHQL/WS")
Rel_L(api_gateway, auth_service, "Uses", "gRPC")
Rel(api_gateway, payment_service, "Uses", "REST")
Rel(api_gateway, project_service, "Uses", "GRAPHQL")
Rel(api_gateway, chat_service, "Uses", "WS")
Rel(api_gateway, notification_service, "Uses", "WS")
Rel(notification_service, kafka, "Uses", "Kafka")
Rel(notification_service, redis,)
Rel(notification_service, firebase, "Uses", "REST")
Rel(chat_service, kafka, "Uses", "Kafka")
Rel(chat_service, redis,)
Rel(project_service, kafka, "Uses", "Kafka")
Rel(project_service, project_db, )
Rel(auth_service, user_db, )
Rel(payment_service, payment_db, )
Rel_R(chat_service, chat_db, )
@enduml