@startuml erd_project
' ERD для сущностей, связанных с проектами

entity Project {
  *id: integer
  ..
  *title: string
  *description: string
  *goal_amount: integer
  *current_amount: integer
  *created_at: datetime
  updated_at: datetime
  *user_id: integer
  *category_id: integer
}

entity Category {
  *id: integer
  ..
  *name:string
}

entity Campaign {
  *id: integer
  ..
  *description: string
  *created_at: datetime
  updated_at: datetime
  *project_id: integer
}

entity News {
  *id: integer
  ..
  *title: string
  *content: text
  *created_at: datetime
  updated_at: datetime
  *user_id: integer
  *project_id: integer
  *score_id: integer
}

entity Comment {
  *id: integer
  ..
  *content: text
  *created_at: datetime
  updated_at: datetime
  *user_id: integer
  *project_id: integer
}

entity Score {
  *id: integer
  ..
  *is_liked: boolean
  *created_at: datetime
  updated_at: datetime
  *user_id: integer
  *news_id: integer
}

Project ||--o{ Comment : "has"
Project ||--o{ News : "has"
Project ||--o{ Campaign : "has"
Project ||--o{ Category : "belongs to"
News ||--o{ Score : "gives"
@enduml